language: python
python:  
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - black --check .
  - coverage run manage.py test
after_script:
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"
  app: "swe1"
  env: "swe1-env"
  bucket_name: $BUCKET
  on:
    all_branches: true

